$axure.loadCurrentPage({
  "url":"新增.html",
  "generationDate":new Date(1449554592281.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ea087ad68f243059c8ca5c18d878d61",
    "type":"Axure:Page",
    "name":"新增",
    "notes":{
      "默认":"<p><span>部门磨</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a6b84c1acc2e4e23aa6ef843cc410728",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":38},
            "size":{
              "width":280,
              "height":425},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3cae5be1d8345cfa2bc2a8c248c0fb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":38},
                "size":{
                  "width":280,
                  "height":425},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增/u0.png"}},
{
          "id":"1ef278ef315b42d28369606ad87e5fd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFF5F5F5},
{
                  "color":0xFFF5F5F5},
{
                  "color":0xFFE8E8E8},
{
                  "color":0xFFE8E8E8}]},
            "size":{
              "width":280,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f49bf2a270204c39af2a0f7c49cd9319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFF5F5F5},
{
                      "color":0xFFF5F5F5},
{
                      "color":0xFFE8E8E8},
{
                      "color":0xFFE8E8E8}]},
                "size":{
                  "width":280,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增/u2.png"}},
{
          "id":"46e9edabc6104336ad78253e1e8a16b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":49},
            "size":{
              "width":49,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad248dc401b4b0d8e57ec6b5b1820c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":49},
                "size":{
                  "width":49,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59f5494fa9294532a9a35edffc5948b8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":49},
            "size":{
              "width":149,
              "height":22}},
          "adaptiveStyles":{
},
          "annotation":{
            "描述":"默认加载上个页面选择的部门"}},
{
          "id":"2687042539824d5cbf8887cb398f9c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":82},
            "size":{
              "width":49,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c47b489fced54a61a04e26b83fe667ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":82},
                "size":{
                  "width":49,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca75d3715d79449298fbcd27935d261d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":82},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
},
          "annotation":{
            "描述":"模糊查询姓名，下方显示姓名和账号名"}},
{
          "id":"0c455a7cc1164a3ab3bbf0cd1ea32fc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":117},
            "size":{
              "width":49,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c131df293ae14211a2e51893caa3c81b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":117},
                "size":{
                  "width":49,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ca0deab0a514f109eb9f71cf7bd6ead",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":117},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
},
          "annotation":{
            "描述":"选择姓名后自动带出对应账号的岗位名称<br>职务可以任意修改"}},
{
          "id":"507039f732b9452c90d61a103994a16a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":28,
              "y":152},
            "size":{
              "width":69,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82f56cf3eca4fda900b72d5fb6c5b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":28,
                  "y":152},
                "size":{
                  "width":69,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f8b2e19985649aaa8405efb6d9f0196",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":152},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1d1bcf515268437da8020729908da274",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":16,
              "y":187},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfff8d422a894c7db9964f6c3a5708be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":16,
                  "y":187},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"734277dae01941d6b64d909300330e51",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":187},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"78d23111fb654638979ca10262b09437",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":16,
              "y":222},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bace91154a1541978523cc55dedf0149",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":16,
                  "y":222},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fd6d6b9d3df49ec933d82f71ed70c99",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":222},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a5063a4f7af34b06945f52526fabbcd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":16,
              "y":257},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e22a9a648be94bdda301681148afd205",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":16,
                  "y":257},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0045e7f47684eaf80a9ef9572bf3446",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":257},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1c4c07cd5b4c4d8db2a401bb7e25b8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":16,
              "y":290},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7712f04a2b0e4b8d816acb736a18facf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":16,
                  "y":290},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c39443c0180460ca8eeb42e5b6cfcf8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":290},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"df29de4644a24c26a8454e5eb0af798b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":16,
              "y":325},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7699c21d94ff4516b618b881ffe29a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":16,
                  "y":325},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6965d7bf8fcf4ddea6be341e5b47f894",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":325},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"003232bfbc5c4e9cb6bf4b6a3ab9ceb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":358},
            "size":{
              "width":49,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880ab7c7bef84f8b814980c522ee8468",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":358},
                "size":{
                  "width":49,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07d486005b694120b8f2c5ed75609c59",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":358},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f013e927d89445ae97cb24508115d81a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":393},
            "size":{
              "width":49,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e1a2373e938427789fd88b3c0774675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":393},
                "size":{
                  "width":49,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05c53776e69542c3bfe3e37118a51155",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":393},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e73711b5bb242fc8e06407b306045bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":48,
              "y":428},
            "size":{
              "width":49,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31902719cc74456e93658d9d67960c1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":48,
                  "y":428},
                "size":{
                  "width":49,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45dac669d41c449eb30f3b876c7322d0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":428},
            "size":{
              "width":149,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a2e7cc0583a64d3e8546b18a51a412fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFC4EDFF},
            "location":{
              "x":0,
              "y":462},
            "size":{
              "width":280,
              "height":38},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFDDDDDD}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd36bfdd95b9492cbe708c119c0089b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC4EDFF},
                "location":{
                  "x":0,
                  "y":462},
                "size":{
                  "width":280,
                  "height":38},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFDDDDDD}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增/u40.png"}},
{
          "id":"3e8c4e5fb72c452193d1e789fc0684a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF285E8E,
              "opacity":1},
            "lineSpacing":"24px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2D6CA2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2D6CA2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF2B669A}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFC4EDFF},
            "textShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":-1,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.2}},
            "location":{
              "x":174,
              "y":467},
            "size":{
              "width":43,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF285E8E},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":1,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0666666666666667}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b722638339f1431fa0d1b8904336b98d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E,
                  "opacity":1},
                "lineSpacing":"24px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2D6CA2},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF285E8E}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2D6CA2},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF2B669A}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC4EDFF},
                "textShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":-1,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.2}},
                "location":{
                  "x":174,
                  "y":467},
                "size":{
                  "width":43,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":1,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0666666666666667}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待1毫秒",
                      "waitTime":1},
{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增/u42.png",
            "mouseOver~":"images/新增/u42_mouseOver.png",
            "mouseDown~":"images/新增/u42_mouseDown.png"}},
{
          "id":"d50bafa02f34401285e28ab615a7d6ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF285E8E,
              "opacity":1},
            "lineSpacing":"24px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2D6CA2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E}},
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF2D6CA2},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF2B669A}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFC4EDFF},
            "textShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":-1,
              "blurRadius":0,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.2}},
            "location":{
              "x":227,
              "y":467},
            "size":{
              "width":43,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF285E8E},
            "cornerRadiusTopLeft":"6",
            "outerShadow":{
              "on":true,
              "offsetX":0,
              "offsetY":1,
              "blurRadius":1,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.0666666666666667}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c704dd7521bc4580a259db7ef03671b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E,
                  "opacity":1},
                "lineSpacing":"24px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2D6CA2},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF285E8E}},
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF2D6CA2},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF2B669A}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC4EDFF},
                "textShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":-1,
                  "blurRadius":0,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.2}},
                "location":{
                  "x":227,
                  "y":467},
                "size":{
                  "width":43,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF285E8E},
                "cornerRadiusTopLeft":"6",
                "outerShadow":{
                  "on":true,
                  "offsetX":0,
                  "offsetY":1,
                  "blurRadius":1,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.0666666666666667}}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待1毫秒",
                      "waitTime":1}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增/u42.png",
            "mouseOver~":"images/新增/u42_mouseOver.png",
            "mouseDown~":"images/新增/u42_mouseDown.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a6b84c1acc2e4e23aa6ef843cc410728":{
      "scriptId":"u0"},
    "a3cae5be1d8345cfa2bc2a8c248c0fb5":{
      "scriptId":"u1"},
    "1ef278ef315b42d28369606ad87e5fd2":{
      "scriptId":"u2"},
    "f49bf2a270204c39af2a0f7c49cd9319":{
      "scriptId":"u3"},
    "46e9edabc6104336ad78253e1e8a16b0":{
      "scriptId":"u4"},
    "2ad248dc401b4b0d8e57ec6b5b1820c0":{
      "scriptId":"u5"},
    "59f5494fa9294532a9a35edffc5948b8":{
      "scriptId":"u6"},
    "2687042539824d5cbf8887cb398f9c44":{
      "scriptId":"u7"},
    "c47b489fced54a61a04e26b83fe667ab":{
      "scriptId":"u8"},
    "ca75d3715d79449298fbcd27935d261d":{
      "scriptId":"u9"},
    "0c455a7cc1164a3ab3bbf0cd1ea32fc6":{
      "scriptId":"u10"},
    "c131df293ae14211a2e51893caa3c81b":{
      "scriptId":"u11"},
    "0ca0deab0a514f109eb9f71cf7bd6ead":{
      "scriptId":"u12"},
    "507039f732b9452c90d61a103994a16a":{
      "scriptId":"u13"},
    "b82f56cf3eca4fda900b72d5fb6c5b75":{
      "scriptId":"u14"},
    "3f8b2e19985649aaa8405efb6d9f0196":{
      "scriptId":"u15"},
    "1d1bcf515268437da8020729908da274":{
      "scriptId":"u16"},
    "dfff8d422a894c7db9964f6c3a5708be":{
      "scriptId":"u17"},
    "734277dae01941d6b64d909300330e51":{
      "scriptId":"u18"},
    "78d23111fb654638979ca10262b09437":{
      "scriptId":"u19"},
    "bace91154a1541978523cc55dedf0149":{
      "scriptId":"u20"},
    "1fd6d6b9d3df49ec933d82f71ed70c99":{
      "scriptId":"u21"},
    "a5063a4f7af34b06945f52526fabbcd5":{
      "scriptId":"u22"},
    "e22a9a648be94bdda301681148afd205":{
      "scriptId":"u23"},
    "a0045e7f47684eaf80a9ef9572bf3446":{
      "scriptId":"u24"},
    "1c4c07cd5b4c4d8db2a401bb7e25b8aa":{
      "scriptId":"u25"},
    "7712f04a2b0e4b8d816acb736a18facf":{
      "scriptId":"u26"},
    "5c39443c0180460ca8eeb42e5b6cfcf8":{
      "scriptId":"u27"},
    "df29de4644a24c26a8454e5eb0af798b":{
      "scriptId":"u28"},
    "7699c21d94ff4516b618b881ffe29a95":{
      "scriptId":"u29"},
    "6965d7bf8fcf4ddea6be341e5b47f894":{
      "scriptId":"u30"},
    "003232bfbc5c4e9cb6bf4b6a3ab9ceb7":{
      "scriptId":"u31"},
    "880ab7c7bef84f8b814980c522ee8468":{
      "scriptId":"u32"},
    "07d486005b694120b8f2c5ed75609c59":{
      "scriptId":"u33"},
    "f013e927d89445ae97cb24508115d81a":{
      "scriptId":"u34"},
    "3e1a2373e938427789fd88b3c0774675":{
      "scriptId":"u35"},
    "05c53776e69542c3bfe3e37118a51155":{
      "scriptId":"u36"},
    "2e73711b5bb242fc8e06407b306045bb":{
      "scriptId":"u37"},
    "31902719cc74456e93658d9d67960c1f":{
      "scriptId":"u38"},
    "45dac669d41c449eb30f3b876c7322d0":{
      "scriptId":"u39"},
    "a2e7cc0583a64d3e8546b18a51a412fb":{
      "scriptId":"u40"},
    "bd36bfdd95b9492cbe708c119c0089b4":{
      "scriptId":"u41"},
    "3e8c4e5fb72c452193d1e789fc0684a1":{
      "scriptId":"u42"},
    "b722638339f1431fa0d1b8904336b98d":{
      "scriptId":"u43"},
    "d50bafa02f34401285e28ab615a7d6ee":{
      "scriptId":"u44"},
    "c704dd7521bc4580a259db7ef03671b4":{
      "scriptId":"u45"}}});